name: Docker build and push workflow
on:
  workflow_call:
    inputs:
      dockerhub_username:
        description: 'Docker Hub username'
        required: true
        type: string
      image_repo:
        description: 'Docker Hub image repository. Defaults to the repository name if not provided.'
        required: false
        type: string
      files_to_hash:
        description: 'List of files to check for changes (space or newline separated). Defaults to composer.lock if not provided.'
        required: false
        type: string
    secrets:
      dockerhub_token:
        description: 'Docker Hub token'
        required: true
      dp_ai_virtual_key:
        description: 'DevPanel AI Virtual Key'
        required: false
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build-application:
    runs-on: ubuntu-latest
    services:
      webserver:
        image: devpanel/php:8.3-base-ai
        env:
          DP_APP_ID: ${{ github.repository }}
          APP_ROOT: '/var/www/html'
          WEB_ROOT: '/var/www/html/web'
          CODES_USER_DATA_DIR: '/var/www/html/.vscode'
          CODES_WORKING_DIR: '/var/www/html'
          APACHE_RUN_USER: 'www'
          APACHE_RUN_GROUP: 'www'
          CODES_ENABLE: 'yes'
          DB_HOST: mysql
          DB_PORT: 3306
          DB_ROOT_PASSWORD: root
          DB_NAME: drupaldb
          DB_USER: user
          DB_PASSWORD: password
          DB_DRIVER: mysql
          DP_AI_VIRTUAL_KEY: ${{ secrets.dp_ai_virtual_key || null }}
        ports:
          - 80:80
        volumes:
          - ${{ github.workspace }}:/app/
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_USER: user
          MYSQL_PASSWORD: password
          MYSQL_DATABASE: drupaldb
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -u root --password=root"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    steps:
      - name: Restore file hash cache
        if: ${{ github.event_name != 'push' }}
        id: cache
        uses: actions/cache@v4
        with:
          path: .files_hash.cache
          key: files-hash:${{ inputs.image_repo || github.repository }}:${{ github.ref_name }}

      - name: Read cached hash value
        if: steps.cache.outputs.cache-hit
        id: read_cached_hash
        run: |
          echo "cached_hash=$(cat .files_hash.cache)" >> $GITHUB_OUTPUT
        shell: bash

      - uses: drupalforge/docker_publish_action@main
        id: publish
        env:
          WEBSERVER: ${{ job.services.webserver.id }}
        with:
          dockerhub_username: ${{ inputs.dockerhub_username }}
          dockerhub_token: ${{ secrets.dockerhub_token }}
          image_repo: ${{ inputs.image_repo || null }}
          files_to_hash: ${{ inputs.files_to_hash || null }}
          cached_hash: ${{ steps.read_cached_hash.outputs.cached_hash || null }}

      - name: Save new hash to cache file
        id: save_hash_file
        if: steps.publish.outputs.files_hash
        run: |
          echo "${{ steps.publish.outputs.files_hash }}" > .files_hash.cache
        shell: bash

      - name: Save hash to cache
        if: steps.save_hash_file.conclusion == 'success'
        uses: actions/cache@v4
        with:
          path: .files_hash.cache
          key: files-hash:${{ inputs.image_repo || github.repository }}:${{ github.ref_name }}:${{ github.run_id }}:${{ github.run_attempt }}
          restore-keys: |
            files-hash:${{ inputs.image_repo || github.repository }}:${{ github.ref_name }}
