name: Docker build and push workflow
on:
  workflow_call:
    inputs:
      dockerhub_username:
        description: 'Docker Hub username'
        required: true
        type: string
      image_repo:
        description: 'Docker Hub image repository. Defaults to the repository name if not provided.'
        required: false
        type: string
      files_to_hash:
        description: 'List of files to check for changes (space or newline separated). Defaults to composer.lock if not provided.'
        required: false
        type: string
    secrets:
      dockerhub_token:
        description: 'Docker Hub token'
        required: true
      dp_ai_virtual_key:
        description: 'DevPanel AI Virtual Key'
        required: false
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_USER: user
          MYSQL_PASSWORD: password
          MYSQL_DATABASE: drupaldb
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -u root --password=root"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    strategy:
      matrix:
        arch: [linux/amd64]
    outputs:
      digest_amd64: steps.publish.outputs.digest
      skip_manifest: steps.publish.outputs.skip_manifest
    steps:
      - name: Restore files hash cache
        if: github.event_name != 'push'
        id: cache
        uses: actions/cache@v4
        with:
          path: .files_hash.cache
          key: files-hash:${{ inputs.image_repo || github.repository }}:${{ github.ref_name }}

      - name: Read cached hash value
        if: steps.cache.outputs.cache-hit
        id: read_cached_hash
        run: |
          echo "cached_hash=$(cat .files_hash.cache)" >> $GITHUB_OUTPUT
        shell: bash

      - uses: drupalforge/docker_publish_action/platform@develop
        id: publish
        env:
          NETWORK: ${{ job.services.mysql.network }}
        with:
          dockerhub_username: ${{ inputs.dockerhub_username }}
          dockerhub_token: ${{ secrets.dockerhub_token }}
          dp_ai_virtual_key: ${{ secrets.dp_ai_virtual_key || null }}
          image_repo: ${{ inputs.image_repo || github.repository }}
          files_to_hash: ${{ inputs.files_to_hash || null }}
          cached_hash: ${{ steps.read_cached_hash.outputs.cached_hash || null }}
          build_platform: ${{ matrix.arch }}

      - name: Save new hash to cache file
        id: save_hash_file
        run: |
          echo "${{ steps.publish.outputs.files_hash }}" > .files_hash.cache
        shell: bash

      - name: Save hash to cache
        uses: actions/cache@v4
        with:
          path: .files_hash.cache
          key: files-hash:${{ inputs.image_repo || github.repository }}:${{ github.ref_name }}:${{ github.run_id }}:${{ github.run_attempt }}
          restore-keys: |
            files-hash:${{ inputs.image_repo || github.repository }}:${{ github.ref_name }}

  create-manifest:
    needs: build-and-push
    if: needs.build-and-push.outputs.skip_manifest != 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Merge digests to JSON
        id: digests
        run: |
          echo 'digests={"linux/amd64": "${{ needs.build-and-push.outputs.digest_amd64 }}" }' >> $GITHUB_OUTPUT

      - uses: drupalforge/docker_publish_action/manifest@develop
        with:
          dockerhub_username: ${{ secrets.dockerhub_username }}
          dockerhub_token: ${{ secrets.dockerhub_token }}
          image_repo: ${{ inputs.image_repo || github.repository }}
          manifest_digests: ${{ steps.digests.outputs.digests }}
